---
- hosts: all
  tasks:
  - name: i want to ping 
    apt:
      name: apache2
      state: present
    when : ansible_os_family=="Debian"  

  - name: i want to start
    service:
      name: apache2
      state: started  
    when : ansible_os_family=="Debian"     